"""Přidání pole datum_narozeni do tabulky user

Revision ID: f0efb12d829a
Revises: f5b21d661486
Create Date: 2025-10-07 13:16:39.417155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0efb12d829a'
down_revision = 'f5b21d661486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datum_narozeni', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('datum_narozeni')

    # ### end Alembic commands ###
